openapi: 3.1.0
info:
  title: Plataforma Cavalls API
  version: 1.0.0
  description: |
    API REST per a la plataforma de venda de cavalls.
    Aquest document segueix un enfocament spec-first. Afegeix/mantén aquí tots els endpoints.

servers:
  - url: http://localhost:3000/api
    description: Local

tags:
  - name: Usuaris
    description: Operacions d'autenticació i gestió d'usuaris (inclòs ADMIN)

components:
  # // Esquemes de seguretat. El backend usa cookie de sessió 'sid'.
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sid
      description: |
        Autenticació per cookie de sessió (sid). El login estableix `Set-Cookie: sid=...`.

paths:
  # ─────────────────────────────────────────────────────────
  # USUARIS
  # Base real al codi: /usuaris (assumit muntat a /api)
  # ─────────────────────────────────────────────────────────
  /usuaris/whoami:
    get:
      tags: [Usuaris]
      summary: Retorna l'usuari autenticat
      security: [{ cookieAuth: [] }]
      responses:
        "200":
          description: Usuari autenticat
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Usuari"
        "401":
          description: No autenticat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

    put:
      tags: [Usuaris]
      summary: Actualitza el perfil de l'usuari autenticat
      security: [{ cookieAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/UsuariUpdate" }
      responses:
        "200":
          description: Perfil actualitzat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Usuari" }
        "400":
          description: Sense canvis o usuari inexistent
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "401":
          description: No autenticat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "500":
          description: Error servidor
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

    delete:
      tags: [Usuaris]
      summary: Elimina el perfil autenticat i tanca la sessió
      description: |
        El backend esborra la sessió de BBDD i expira la cookie `sid`.
      security: [{ cookieAuth: [] }]
      responses:
        "200":
          description: Eliminat i logout correctes
          headers:
            Set-Cookie:
              description: Expira la cookie de sessió `sid`
              schema: { type: string }
          content:
            application/json:
              schema: { $ref: "#/components/schemas/OkResponse" }
        "401":
          description: No autenticat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "404":
          description: Usuari no trobat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /usuaris:
    post:
      tags: [Usuaris]
      summary: Crea un usuari
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/UsuariCreate" }
      responses:
        "201":
          description: Usuari creat
          content:
            application/json:
              schema:
                type: object
                properties:
                  usuari_id: { type: integer, example: 321 }
        "400":
          description: Falten camps o validació
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "409":
          description: Correu duplicat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "500":
          description: Error creant usuari
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

    get:
      tags: [Usuaris]
      summary: Llista tots els usuaris (només dades públiques)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { $ref: "#/components/schemas/Usuari" }
        "500":
          description: Error obtenint usuaris
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /usuaris/{id}:
    get:
      tags: [Usuaris]
      summary: Obté un usuari per ID
      parameters:
        - $ref: "#/components/parameters/UsuariIdParam"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Usuari" }
        "404":
          description: Usuari no trobat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "500":
          description: Error cercant usuari
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

    put:
      tags: [Usuaris]
      summary: Edita un usuari (ADMIN)
      security: [{ cookieAuth: [] }]
      parameters:
        - $ref: "#/components/parameters/UsuariIdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/UsuariUpdate" }
      responses:
        "200":
          description: Usuari actualitzat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Usuari" }
        "404":
          description: Usuari no trobat o sense canvis
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "401":
          description: No autenticat / sense permisos
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "500":
          description: Error actualitzant usuari
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

    delete:
      tags: [Usuaris]
      summary: Elimina un usuari (ADMIN)
      security: [{ cookieAuth: [] }]
      parameters:
        - $ref: "#/components/parameters/UsuariIdParam"
      responses:
        "200":
          description: Eliminat correctament
          content:
            application/json:
              schema: { $ref: "#/components/schemas/OkResponse" }
        "404":
          description: Usuari no trobat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "401":
          description: No autenticat / sense permisos
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "500":
          description: Error eliminant usuari
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /usuaris/login:
    post:
      tags: [Usuaris]
      summary: Inicia sessió (cookie-based)
      description: |
        Retorna l'usuari (sense contrassenya) i estableix la cookie de sessió `sid`.
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/LoginRequest" }
      responses:
        "200":
          description: Login correcte
          headers:
            Set-Cookie:
              description: Cookie de sessió `sid`
              schema: { type: string }
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Usuari" }
        "400":
          description: Falten camps
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "401":
          description: Credencials incorrectes
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "403":
          description: Compte desactivada per administrador
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "500":
          description: Error al fer login
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /usuaris/logout:
    post:
      tags: [Usuaris]
      summary: Tanca sessió
      description: |
        Esborra la sessió a BBDD i expira la cookie `sid`.
      responses:
        "200":
          description: Logout correcte
          headers:
            Set-Cookie:
              description: Expira la cookie `sid`
              schema: { type: string }
          content:
            application/json:
              schema: { $ref: "#/components/schemas/OkResponse" }
        "500":
          description: Error fent logout
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /usuaris/admin/llistat:
    get:
      tags: [Usuaris]
      summary: Llista d'usuaris (ADMIN) amb filtre d'activitat
      security: [{ cookieAuth: [] }]
      parameters:
        - in: query
          name: actiu
          description: Filtra per estat (1 actius, 0 inactius). Si s'omet, retorna tots.
          schema:
            type: string
            enum: ["1", "0"]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { $ref: "#/components/schemas/Usuari" }
        "401":
          description: No autenticat / sense permisos
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "500":
          description: Error obtenint usuaris
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /usuaris/{id}/actiu:
    patch:
      tags: [Usuaris]
      summary: Activa/Desactiva un usuari (ADMIN)
      security: [{ cookieAuth: [] }]
      parameters:
        - $ref: "#/components/parameters/UsuariIdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [actiu]
              properties:
                actiu:
                  description: Estat a aplicar
                  oneOf:
                    - type: boolean
                    - type: integer
                  examples: [true, 1, 0]
      responses:
        "200":
          description: Estat actualitzat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Usuari" }
        "400":
          description: Falta actiu
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "401":
          description: No autenticat / sense permisos
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "404":
          description: Usuari no trobat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "500":
          description: Error actualitzant estat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }


paths:
  /anuncis:
    get:
      tags: [Anuncis]
      summary: Llista d’anuncis
      description: Llista pública d’anuncis.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { $ref: "#/components/schemas/Anunci" }
        "500":
          description: Error obtenint anuncis
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

    post:
      tags: [Anuncis]
      summary: Crea un anunci
      security: [{ cookieAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/AnunciCreate" }
      responses:
        "201":
          description: Creat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Anunci" }
        "401":
          description: No autenticat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "400":
          description: Error de validació o camps
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "500":
          description: Error creant anunci
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /anuncis/{id}:
    get:
      tags: [Anuncis]
      summary: Detall d’un anunci
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer, minimum: 1 }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Anunci" }
        "404":
          description: No trobat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "500":
          description: Error
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

    put:
      tags: [Anuncis]
      summary: Actualitza un anunci (propietari o admin)
      security: [{ cookieAuth: [] }]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer, minimum: 1 }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/AnunciUpdate" }
      responses:
        "200":
          description: Actualitzat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Anunci" }
        "401":
          description: No autenticat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "403":
          description: No autoritzat (no és propietari ni admin)
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "404":
          description: No trobat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

    delete:
      tags: [Anuncis]
      summary: Elimina un anunci (propietari o admin)
      security: [{ cookieAuth: [] }]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer, minimum: 1 }
      responses:
        "200":
          description: Eliminat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/OkResponse" }
        "401":
          description: No autenticat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "403":
          description: No autoritzat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "404":
          description: No trobat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /anuncis/{id}/estat:
    patch:
      tags: [Anuncis]
      summary: Canvia l’estat d’un anunci (ADMIN)
      security: [{ cookieAuth: [] }]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer, minimum: 1 }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/AnunciEstatPatch" }
      responses:
        "200":
          description: Estat canviat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Anunci" }
        "401":
          description: No autenticat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "403":
          description: No autoritzat (només admin)
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "404":
          description: No trobat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /anuncis/{id}/revisions:
    get:
      tags: [Anuncis]
      summary: Historial de revisions (ADMIN)
      security: [{ cookieAuth: [] }]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer, minimum: 1 }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { $ref: "#/components/schemas/RevisioAnunci" }
        "401":
          description: No autenticat
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "403":
          description: No autoritzat (només admin)
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "500":
          description: Error obtenint revisions
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
